### ISSUE TITLE
Remove start_mongo.bash, stop_mongo.bash; establish agnostic test setup

### ISSUE THREAD

**Issue by fireproofsocks** [kobil-systems/mongodb#373]
It is difficult to run tests currently because the repository requires the system to be running in a certain way. Tests are setup by running mongo replicas, but the bash scripts assume that you are running mongo locally.  

It would be better if the code didn't know so much about how or where the mongo instances were running.  The code should only need enough configuration to be able to connect to a mongo instance with sufficient privileges.

Note that the TravisCI config references this script.

Mentioned in Issue #336

**Comment by scottmessinger** [comment]
@fireproofsocks I think this is fixed now!
