### ISSUE TITLE
ElixirLS Dialyzer Issues

### ISSUE THREAD

**Issue by briankariuki** [kobil-systems/mongodb#378]
I'm getting this error on my project. I'm using version 1.0.0. Also when I call. Mongo.find_one() I get warnings regarding the return type of the function

<img width="496" alt="Screenshot 2023-06-17 at 18 16 05" src="https://github.com/elixir-mongo/mongodb/assets/34672053/84275b25-3ca9-473a-9ff4-58935094a663">

**Comment by ankhers** [comment]
I believe the issue is because you are using `'users'` as your collection name. This is a charlist in Elixir. The expected type is a binary. If you change it to `"users"` (double quotes), it may resolve the warning.

**Comment by ankhers** [comment]
I'm going to close this because there has been no response. If this is still an issue after making my suggested change above, please feel free to reopen with additional information.
